# -*- coding: utf-8 -*-
"""Activity1_Pandas_PRELIMS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IGrB_eek2kM2_ELPBraqpncfJDIKEkI8

import the pandas
"""

import pandas as pd

df = pd.DataFrame({'name':['Reyna','Jett','Sage'],
                  'age':[20,30,40],
                  'pet':['Snake', 'Lion', 'Tiger']})
df

print(df.columns)
print(df.index)

print(df['name'])
print(df.name)

df[['name','pet']]

df.iloc[1 : 2]

df.sort_values('pet', inplace=True, ascending=True)
df

df.loc[0] #index based

df.iloc[0]#relative position based indexing

df.iloc[:,2]

df.iloc[-1:]