# -*- coding: utf-8 -*-
"""activity1_part2_PANDAS_PRELIMS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sy06MTICw-6zHAuhut7F-PWAcUl1AC4z
"""

import pandas as pd

df = pd.DataFrame ({'studentno': [100,130,119,92,35],
                    'stnname': ['jett','sage','brim','reyna','chamber'],
                    'course': ['BAC','CCS','EDUC','COENG','CBAA']})
df

print("The name of the first column is: ")
print(df.columns[0])

df.sort_values('course', inplace=True, ascending=False)
df

df.iloc[-1]

df[['stnname','studentno','course']]