# -*- coding: utf-8 -*-
"""LU_DATA_Gallardo_midterm_Activity2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MUhGoTjHhTZRd0eTM3LZOZZe5lC8hPXh

MARY JOSAN GALLARDO
BSCS-DS 2C

MARCH 9, 2026
11:1:00PM

LU DATA ACTIVITY KINDLY SCROLL DOWN PO
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import pandas as pd
import random
import math
import time
from sklearn.linear_model import LinearRegression, BayesianRidge
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, mean_absolute_error
import datetime
import operator
# %matplotlib inline
import warnings
import seaborn as sns
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
warnings.filterwarnings("ignore")

df = pd.read_csv("/content/Laguna-University-Students-Data.csv")
df

from google.colab import drive
drive.mount('/content/drive')

df.dtypes

sns.relplot(x='Programs ', y='Programs ', data=df, hue='Pila')

"""**ACTIVITY:    LU DATA**  
MARCH 11, 2026  

**INSTRUCTION**
# Identify numerical columns for enrollment figures
# Remove the 'Total:' row as it represents an aggregate sum and not an individual program
# Fill any missing enrollment values (NaN) with 0 in enrollment columns
# Calculate Total Enrollment for each program
# Sort programs by total enrollment in descending order and get the top 5
"""

# Step 1:
df = df[df['Programs '].str.strip().str.lower() != 'total:']

# Step 2:
enrollment_cols = df.columns.drop('Programs ')

# Step 3:
df[enrollment_cols] = df[enrollment_cols].fillna(0)

# Step 4:
df['Total_Enrollment'] = df[enrollment_cols].sum(axis=1)

# Step 5:
top5 = df.sort_values(by='Total_Enrollment', ascending=False).head(5)

# Display Top 5 programs
print("Top 5 Programs by Total Enrollment:")
print(top5[['Programs ', 'Total_Enrollment']])

"""nag add lang ako dito pero hindi namn po kasama tong visual tnx po"""

sns.barplot(
    x='Total_Enrollment',
    y='Programs ',
    data=top5,
    palette='viridis'
)
plt.title("Top 5 Programs by Total Enrollment")
plt.xlabel("Total Enrollment")
plt.ylabel("Programs")
plt.show()